### ISSUE TITLE
Global Optimal Grouping at Movie Level

### ISSUE THREAD

**Issue by najmehs** [AnyiRao/SceneSeg#11]
Hi,

Thanks for publishing your helpful code. I was wondering whether you have released the code for section 4.4 in the paper which is about the global optimization?

Thanks!

**Comment by anyirao** [comment]
Hi @najmehs ,

Thanks for your interest. 

Currently, the codebase does not contain global optimal grouping due to commercial and property rights issues. Here we provide some similar codes for reference. The global optimization function refers to the 2014 CVPR storygraph. They have a Matlab implementation. It is not difficult to write a python version of DP by hand: https://github.com/makarandtapaswi/StoryGraphs_CVPR2014. 

Best,
Anyi
